---
# chocomilk vars

# Package Changelog
changelog: 'https://www.microsoft.com/en-us/download/details.aspx?id=49117'

# Regex for Version
version: "{{ register_changelog.content |
  regex_search('.*Version (\\d+).*') |
  regex_search('(\\d+)(.)(\\d+)(.)(\\d+)(.)(\\d+)')
  }}"

# Download URL
url: "https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_{{ version | regex_replace('16.0.', '') | regex_replace('\\.', '-')   }}.exe"

searchreplace:
  'tools/chocolateyinstall.ps1':
    - regwxp: (^\s*[$]*urlPackage\s*=\s*)('.*')
      replace: '$urlPackage = "{{ url }}"'
    - regwxp: (^\s*[$]*checksumPackage\s*=\s*)('.*')
      replace: '$checksumPackage = "{{ file_hash }}"'

# readme to description
readme:
  start: 6
  end: 18

# deploy
deploy:
  - provider: chocolatey
    repository: 'https://nuget.itigo.tech/upload'
    key: "{{ lookup('env','CHOCOLATEY_ITIGO_API_KEY') }}"
  - provider: chocolatey
    repository: 'https://push.chocolatey.org/'
    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: github
    name: 'itigo-bot'
    email: 'chocomilk@itigo.ch'
    url: github.com/itigoag/chocolatey.microsoft-office-deployment.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: 'https://matters.itigo.tech'
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: 'software-packages'
